### ISSUE TITLE
BayesNet.read_bif can create inconsistent graph

### ISSUE THREAD

**Issue by quaxquax** [artiste-qb-net/quantum-fog#10]
I created a simple Monty Hall B-net BIF. It contains an error in the potential definition for the Monty_Opens node.  This error is not caught when the BIF is loaded.  

When running the Brute Force Enumeration Engine this creates unexpected results but no errors, fortunately the Join Tree Engine throws errors that show where this is coming from. 

QFog should not accept an incorrect BIF file as valid input. This also merits some further investigation to see if one can create such an inconsistent graph through the API.

The corrupt/corrupting BIF file is attached.
[Monty_Hall.txt](https://github.com/artiste-qb-net/quantum-fog/files/648287/Monty_Hall.txt)

**Comment by rrtucci** [comment]
fixed
