### ISSUE TITLE
HTML table output in Jupyter

### ISSUE THREAD

**Issue by quaxquax** [artiste-qb-net/quantum-fog#11]
In my branch I extended the EnumerationEngine class to accept an additional argument _**print_format**_ (-> screenshot). It defaults to _text_ but when specifying _HTML_ it produces a joint distribution table as shown in the attached screen-shot. 

If you agree that this is a nice feature to have, I will incorporate this as I go along for all other print output that could be wrapped into a HTML table.

![screenshot from 2016-12-15 00-28-11](https://cloud.githubusercontent.com/assets/5298290/21212846/3fb9cc5e-c25e-11e6-9416-0e0620c48fc1.png)

**Comment by rrtucci** [comment]
Don't change master yet. I don't see your branch as public. Your branch is not even up to date becauseI had used both the words do_print and verbose in different places and I changedthem all to verbose for consistency. Your jpeg shows the old do_print--- notifications@github.com wrote:From: Henning Dekant <notifications@github.com>To: artiste-qb-net/quantum-fog <quantum-fog@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [artiste-qb-net/quantum-fog] HTML table output in Jupyter (#11)Date: Wed, 14 Dec 2016 21:39:00 -0800In my branch I extended the EnumerationEngine class to accept an additional argument print_format (-> screenshot). It defaults to text but when specifying HTML it produces a joint distribution table as shown in the attached screen-shot.
If you agree that this is a nice feature to have, I will incorporate this as I go along for all other print output that could be wrapped into a HTML table.

**Comment by rrtucci** [comment]
I added 99% of the changes in your jupyter_output_enhancements branch, including your notebook for the meetup you held in Toronto on Dec-19-2016
